const api =[
    {subject: "Photography Basic", about: "Photography is the art, application, and practice of creating durable images by recording light, either electronically by means of an image sensor, or chemically by means of a light-sensitive material such as photographic film. It is employed in many fields of science, manufacturing (e.g., photolithography), and business, as well as its more direct uses for art, film and video production, recreational purposes, hobby, and mass communication.",
    price: 45, img:"https://images.unsplash.com/photo-1510215744419-742d9dce947f?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=387&q=80"
},
    {subject: "Digital intermediate Photography", about: "It often replaces or augments the photochemical timing process and is usually the final creative adjustment to a movie before distribution in theaters. It is distinguished from the telecine process in which film is scanned and color is manipulated early in the process to facilitate editing. However the lines between telecine and DI are continually blurred and are often executed on the same hardware by colorists of the same background. These two steps are typically part of the overall color management process in a motion picture at different points in time. A digital intermediate is also customarily done at higher resolution and with greater color fidelity than telecine transfers.",
    price: 19, img:"https://images.unsplash.com/photo-1590486803833-1c5dc8ddd4c8?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=387&q=80"
},
    {subject: "Image editing", about: "Image editing encompasses the processes of altering images, whether they are digital photographs, traditional photo-chemical photographs, or illustrations. Traditional analog image editing is known as photo retouching, using tools such as an airbrush to modify photographs or editing illustrations with any traditional art medium. Graphic software programs, which can be broadly grouped into vector graphics editors, raster graphics editors, and 3D modelers, are the primary tools with which a user may manipulate, enhance, and transform images. Many image editing programs are also used to render or create computer art from scratch.",
    price: 27, img:"https://images.unsplash.com/photo-1628435600697-6a954dea5055?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=387&q=80"
},
    {subject: "Camera Eqipment", about: "Everyone’s favorite part of photography is camera equipment. I’m kidding, of course — although that is the impression you’ll get from certain photographers. But no one can deny that some gear is necessary in order to take pictures. At the very least, you need a camera and lens, but there are also important considerations like software and other accessories. This article dives into the most necessary and important camera equipment you need for photography, including some of our top recommendations.",
    price: 27, img:"https://images.unsplash.com/photo-1486693326701-1ea88c6e2af3?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1887&q=80"
},
]